### ISSUE TITLE
error in baseline_random.py

### ISSUE THREAD

**Issue by sukun1045** [bknyaz/beauty_vision#1]
Hello, i encounter the following problem, not sure how to fix it

> 500 images and 500 labels read
computing features using random filters
Traceback (most recent call last):
  File "beauty_baseline_random.py", line 152, in <module>
    feat_maps = relu(f2(f1(np.asarray(image_list, dtype='float32').transpose(0,3,1,2))))
  File "/home/sukun/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/sukun/.local/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/sukun/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
RuntimeError: BaseCorrMM: Failed to allocate output of 500 x 24 x 216 x 216
Apply node that caused the error: CorrMM{valid, (1, 1), (1, 1), 1 False}(input, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 1
Inputs types: [TensorType(float64, 4D), TensorType(float64, 4D)]
Inputs shapes: [(500, 3, 224, 224), (24, 3, 9, 9)]
Inputs strides: [(1204224, 8, 5376, 24), (1944, 648, -72, -8)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [['output']]
Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "beauty_baseline_random.py", line 150, in <module>
    f1 = theano.function([input], conv2d(input, W))
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by bknyaz** [comment]
Hi, 
The shape of feat_maps must be (500, 24, 13, 13), so most likely you are not resizing the images and the code crashes because your feature maps are too large and do not fit into memory. The key phrase in your error is: "Failed to allocate output".

**Comment by sukun1045** [comment]
Yeah it is the memory problem. I change to another laptop and it works. Thank you.
